### ISSUE TITLE
error in script RePrimAnd/ET_interface/thorns/RePrimAnd/src/build.sh

### ISSUE THREAD

**Issue by bgiacoma** [wokast/RePrimAnd#21]
build.sh looks into a directory named RePrimAnd (line 17 NAME=RePrimAnd), but the tarball RePrimAnd.tar contains a directory named RePrimAnd-1.3 (instead of RePrimAnd) causing the failure of the build process of the RePrimAnd thorn.

**Comment by wokast** [comment]
Thanks for reporting. This was caused by a mistake when creating the archive, the folder should not have the version name in it. This will be fixed in the upcoming release. A simple workaround that does not require editing build scripts is to unpack the archive, rename the folder from RePrimAnd-1.3 to RePrimAnd , and repack it.

**Comment by wokast** [comment]
fixed in v1.4
